name: Build Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12'

    - name: Install dependencies
      run: npm install

    - name: Set up Rust
      run: rustup toolchain install stable --profile minimal --no-self-update

    - name: apt-get update
      run: sudo apt-get update  

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev pkg-config build-essential libgtk-3-dev curl libssl-dev libsoup-3.0 javascriptcoregtk-4.1 webkit2gtk-4.1 libayatana-appindicator3-1

    - name: Build frontend
      run: npm run build

    - name: Set up cache
      uses: Swatinem/rust-cache@v2
    - name: Building backend
      run: |
            cargo check
            cargo build --release
            working-directory: src/tauri
